package ridi.web.util.errors;

public enum Errors {
    INVALID_TOKEN_ERROR,
    TOKEN_EXPIRED_ERROR,
    HEADER_WITHOUT_BEARERTOKEN_ERROR, WRONG_ARGUMENT_ERROR, ENTITY_NOT_FOUND_ERROR, SERVICE_ERROR, USER_WITHOUT_GRANT_ERROR, UNINTELIGIBLE_REQUEST_ERROR, WRONG_RESOURCE_ERROR, USER_NOTFOUND_ERROR
}
